# Generated by Django 6.0.3 on 2026-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetConnecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(max_length=50)),
                ('animal_concerne', models.CharField(blank=True, max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batterie', models.IntegerField(default=100)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
    ]
