# Generated by Django 6.0.3 on 2026-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetconnecte',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='alimentation',
            field=models.CharField(default='Secteur', max_length=50),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='capteurs_liste',
            field=models.CharField(default='Température, Humidité', max_length=200),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='conso_energie',
            field=models.CharField(default='5W/h', max_length=50),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='derniere_interaction',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='id_unique',
            field=models.CharField(default='ID-TEMP', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='objets/'),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='mode',
            field=models.CharField(default='Automatique', max_length=50),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='signal_wifi',
            field=models.CharField(default='Fort', max_length=50),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='valeur_actuelle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
