# Generated by Django 6.0.3 on 2026-04-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_objetconnecte_adresse_ip_objetconnecte_alimentation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetconnecte',
            name='prix',
        ),
    ]
