# Generated by Django 6.0.3 on 2026-04-27 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_objetconnecte_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
                ('Consommation', models.FloatField()),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_conso', to='core.objetconnecte')),
            ],
        ),
    ]
