# Generated by Django 6.0.3 on 2026-04-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consommation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consommation',
            old_name='Consommation',
            new_name='consommation',
        ),
    ]
