# Generated by Django 6.0.3 on 2026-04-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_statistiques'),
        ('core', '0005_rename_consommation_consommation_consommation'),
    ]

    operations = [
    ]
