# Generated by Django 6.0.3 on 2026-04-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260428_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consommation',
        ),
    ]
