# Generated by Django 6.0.3 on 2026-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_consommation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetconnecte',
            name='alimentation',
            field=models.CharField(choices=[('batterie', 'Batterie'), ('secteur', 'Secteur')], default='secteur', max_length=10),
        ),
        migrations.AlterField(
            model_name='objetconnecte',
            name='categorie',
            field=models.CharField(choices=[('iot', 'IOT'), ('produit', 'Produit'), ('service', 'Service')], max_length=10),
        ),
        migrations.AlterField(
            model_name='objetconnecte',
            name='conso_energie',
            field=models.FloatField(default='5'),
        ),
        migrations.AlterField(
            model_name='objetconnecte',
            name='mode',
            field=models.CharField(choices=[('auto', 'Automatique'), ('man', 'Manuel'), ('eco', 'Eco')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='objetconnecte',
            name='signal_wifi',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('fort', 'Fort'), ('moyen', 'Moyen'), ('faible', 'Faible')], default='fort', max_length=10),
        ),
    ]
