# Generated by Django 4.2.11 on 2026-04-16 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(default=datetime.date(2006, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
