# Generated by Django 4.2.11 on 2026-04-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_date_naissance_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_naissance',
            new_name='birthdate',
        ),
    ]
